name: CI

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    name: Test on PHP ${{ matrix.php-version }}
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2

      - name: ⚙️ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}

      - name: 🕵️ Code Sniffer
        run: ./vendor/bin/phpcs -vvv

      - name: 🔎 Static Analysis
        run: ./vendor/bin/phpstan -vvv

      - name: 🧪 Unit Tests
        run: ./vendor/bin/phpunit -vvv
