name: CI

on: [push]

jobs:
  sniff:
    name: 🕵️ Code Sniffer (PHP ${{ matrix.php-version }})
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: 🕵️ Run Code Sniffer
        run: ./vendor/bin/phpcs -vvv

  analyze:
    name: 🔎 Static Analysis (PHP ${{ matrix.php-version }})
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: 🔎 Perform Static Analysis
        run: ./vendor/bin/phpstan -vvv

  test:
    name: 🧪 Unit Testing (PHP ${{ matrix.php-version }})
    strategy:
      fail-fast: false
      matrix:
        php-version: ["7.4", "8.0"]
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v2
      - name: ⚙️ Install composer
        uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php-version }}
      - name: 🧪 Run Tests
        run: ./vendor/bin/phpunit -vvv
